### ISSUE TITLE
Support for Generic Host Builder

### ISSUE THREAD

**Issue by mprigge** [thomaslevesque/AspNetCore.AsyncInitialization#16]
Would you be interested in introducing support for the generic host builder for this package? Unless I'm missing something, it'd just need another extension method that extends `IHost` instead of `IWebHost`. I can contribute something if that'd be helpful.

**Comment by mprigge** [comment]
I just realized that'd add a cross dependency on `Microsoft.Extensions.Hosting.IHost` that might be undesirable in a package designed for the WebHost. Might be best addressed in an extension, but then that'd loop back to the issue of `RootInitializer` being internal.

**Comment by thomaslevesque** [comment]
Hi @mprigge,

Thanks for the suggestion. I guess it would make sense to also support the generic host. However:
1. The name of the package implies that it's for ASP.NET Core; for an app that doesn't have anything to do with ASP.NET Core, it would be confusing to reference a package with "AspNetCore" in its name.
2. It has ASP.NET Core specific dependencies. Bringing in those dependencies in a non-ASP.NET Core app would be annoying.
3. the whole `IWebHost`/`IHost` story is a mess. They represent the same concept, have almost the same API, but they live in different packages and different namespaces. Referencing both in the same project would be messy. (I think this is going to be fixed in .NET Core 3.0, though)

For now, I think the best course would be to split the project into several packages:
- one with the common code (dependency registrations, `RootInitializer`)
- one with the WebHost specific code (the `InitAsync` method)
- one with the generic Host specific code (another `InitAsync` method)

In fact, the only difference between the two `InitAsync` methods would be the type of the `host` parameter... And even then, the only thing I do with it is access its `Services` property. So even most of that code could be shared.

> the issue of `RootInitializer` being internal

Not much of an issue. I could make it public, or use `InternalsVisibleTo` to make it visible to the relevant assemblies.

I need to give some thought to the naming, though. Probably find a new name that doesn't mention AspNetCore.

**Comment by alexdresko** [comment]
> Probably find a new name that doesn't mention AspNetCore.

That's probably what I'd do. For the time being, I'm just going to borrow some of the code in this repo until it works with generic host.

**Comment by cypressious** [comment]
It seems that ASP.NET Core 3 will use the Generic Host.

https://docs.microsoft.com/en-US/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#hostbuilder-replaces-webhostbuilder

**Comment by thomaslevesque** [comment]
> It seems that ASP.NET Core 3 will use the Generic Host.

Indeed. I just released a variant of this project that uses the generic host. It should work for ASP.NET Core 3 apps and for .NET Core 2.1+ apps that use the generic host.

https://github.com/thomaslevesque/Extensions.Hosting.AsyncInitialization

> For now, I think the best course would be to split the project into several packages:
> * one with the common code (dependency registrations, `RootInitializer`)
> * one with the WebHost specific code (the `InitAsync` method)
> * one with the generic Host specific code (another `InitAsync` method)

I gave up on the idea of having a package with the common code. ASP.NET Core 3.0 is coming soon, ASP.NET Core 2.x will eventually be deprecated, and this project is probably not going to evolve very often, so it's not a big issue to maintain both packages, and it makes things simpler.
