### ISSUE TITLE
Add support for the new IHost interface

### ISSUE THREAD

**Issue by labsilva** [thomaslevesque/AspNetCore.AsyncInitialization#17]
In ASP.NET Core 3.0 they changed the default host builder from WebHost (IWebHost) to Host (IHost).

To add support for it, it should be just a matter of adding a new extension method that extends IHost.

I can make a pull request if you prefer.

**Comment by thomaslevesque** [comment]
Hey @labsilva,

Thanks for your interest. This was already raised in #16. I didn't want to support `IHost` and `IWebHost` in the same library, because it would pull the ASP.NET Core dependencies even for people who just use the generic host.

I made a new project specifically for the generic host:

https://github.com/thomaslevesque/Extensions.Hosting.AsyncInitialization

**Comment by labsilva** [comment]
Hi @thomaslevesque,
Very sorry, should've searched better before creating a new issue.
Thanks!
